/// Flutter icons MyBed
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyBed
///      fonts:
///       - asset: fonts/MyBed.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyBed {
  MyBed._();

  static const _kFontFam = 'MyBed';
  static const _kFontPkg = null;

  static const IconData bed = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
