/// Flutter icons MyCart
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyCart
///      fonts:
///       - asset: fonts/MyCart.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyCart {
  MyCart._();

  static const _kFontFam = 'MyCart';
  static const _kFontPkg = null;

  static const IconData shopping_cart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
